// Logic and types regarding the TEACHERS table.

import type { PostgrestError, SupabaseClient } from "@supabase/supabase-js";

export type Teacher = {
  id: string           // UUID, mirrors auth.users(id) — not auto-generated by this table
  email: string
  display_name: string
  created_at: string   // ISO 8601 timestamp, auto-set
}

export type InsertTeacher = Pick<Teacher, 'id' | 'email' | 'display_name'>

export async function insertTeacher(
  supabase: SupabaseClient,
  row: InsertTeacher,
): Promise<{ data: Teacher | null; error: PostgrestError | null }> {
  const { data, error } = await supabase
    .from("teachers")
    .insert(row)
    .select("id, email, display_name, created_at")
    .single();

  if (error) {
    return { data: null, error };
  }

  return { data: data as Teacher, error: null };
}
