// Logic and types regarding the TEACHERS table.

export type Teacher = {
  id: string           // UUID, mirrors auth.users(id) — not auto-generated by this table
  email: string
  display_name: string
  created_at: string   // ISO 8601 timestamp, auto-set
}

export type InsertTeacher = Pick<Teacher, 'id' | 'email' | 'display_name'>